[package]
name = "jotter"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.8"
rust_decimal = { version = "1.36.0", features = ["maths"] }
rust_decimal_macros = "1.36.0"

[features]
maths = []
